# Generated by Django 3.0b1 on 2019-10-29 00:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('symdon_auth', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='userlink',
            name='access_token',
            field=models.CharField(default='', max_length=500),
        ),
        migrations.AddField(
            model_name='userlink',
            name='refresh_token',
            field=models.CharField(default='', max_length=500),
        ),
    ]
