# ---
- file:
    path: "{{ root_dir }}"
    state: directory

- file:
    path: "{{ systemd_dir }}"
    state: directory

- file:
    path: "{{ log_dir }}"
    state: directory

- file:
    path: "{{ env_dir }}"
    state: directory

- file:
    path: "{{ static_root }}"
    state: directory

- file:
    path: "{{ nginx_dir }}"
    state: directory

- template:
    src: _env.env
    dest: "{{ root_dir }}/.env"
  notify: 
    - symdon_django_restart

- template:
    src: systemd/_.service
    dest: "{{ systemd_dir }}/{{ service_name }}.service"

- file:
    src: "{{ systemd_dir }}/{{ service_name }}.service"
    dest: "/etc/systemd/system/{{ service_name }}.service"
    state: link

- file:
    src: "{{ log_dir }}"
    dest: "/var/log/{{ service_name }}"
    state: link
    
- git:
    repo: "{{ git_repo }}"
    dest: "{{ src_dir }}"
  notify: 
    - symdon_django_deps
    - symdon_django_migrate
    - symdon_django_collectstatic
    - symdon_django_restart

- command: "python3.7 -m venv {{ venv_dir }}"
  args:
    creates: "{{ venv_dir }}/bin/python"
  notify: 
    - symdon_django_deps
    - symdon_django_restart

- template:
    src: sites-available/_upstream.conf
    dest: "{{ nginx_dir }}/{{ domain }}"
  notify: 
    - symdon_django_nginx_reload


- file:
    src: "{{ nginx_dir }}/{{ domain }}"
    dest: "/etc/nginx/sites-available/{{ domain }}"
    state: link

- file:
    src: "/etc/nginx/sites-available/{{ domain }}"
    dest: "/etc/nginx/sites-enabled/{{ domain }}"
    state: link
  notify: 
    - symdon_django_nginx_reload
    
- name: link static dir
  file:
    src: "{{ static_root }}"
    dest: "{{ www_root }}"
    state: link

