# -*- restclient -*-

# 取得
GET http://127.0.0.1:9090/api/counter/
Content-Type: application/json
Authorization: Bearer eyJ0eXAiOiJKV1QiLCJhbGciOiJIUzI1NiJ9.eyJ1c2VyX2lkIjoxLCJ1c2VybmFtZSI6InN4aW1hZGEiLCJleHAiOjE1MTEwNDg1OTIsImVtYWlsIjoic3hpbWFkYUBnbWFpbC5jb20ifQ.Ln1aWJRWDZg3Rqyaj5CI2xJkxg8sGMFAD3_zp7TgX00

# 取得 (id指定)
GET http://127.0.0.1:9090/api/counter/1/
Content-Type: application/json
Authorization: Bearer eyJ0eXAiOiJKV1QiLCJhbGciOiJIUzI1NiJ9.eyJ1c2VyX2lkIjoxLCJ1c2VybmFtZSI6InN4aW1hZGEiLCJleHAiOjE1MTEwNDg1OTIsImVtYWlsIjoic3hpbWFkYUBnbWFpbC5jb20ifQ.Ln1aWJRWDZg3Rqyaj5CI2xJkxg8sGMFAD3_zp7TgX00

# 作成
POST http://127.0.0.1:9090/api/counter/
Content-Type: application/json
Authorization: Bearer eyJ0eXAiOiJKV1QiLCJhbGciOiJIUzI1NiJ9.eyJ1c2VyX2lkIjoxLCJ1c2VybmFtZSI6InN4aW1hZGEiLCJleHAiOjE1MTEwNDg1OTIsImVtYWlsIjoic3hpbWFkYUBnbWFpbC5jb20ifQ.Ln1aWJRWDZg3Rqyaj5CI2xJkxg8sGMFAD3_zp7TgX00

# 更新
PATCH http://127.0.0.1:9090/api/counter/1/
Content-Type: application/json
Authorization: Bearer eyJ0eXAiOiJKV1QiLCJhbGciOiJIUzI1NiJ9.eyJ1c2VyX2lkIjoxLCJ1c2VybmFtZSI6InN4aW1hZGEiLCJleHAiOjE1MTEwNDg1OTIsImVtYWlsIjoic3hpbWFkYUBnbWFpbC5jb20ifQ.Ln1aWJRWDZg3Rqyaj5CI2xJkxg8sGMFAD3_zp7TgX00

{
  "id": 1,
  "count": 1
}

# 削除
DELETE http://127.0.0.1:9090/api/counter/1/
Content-Type: application/json
Authorization: Bearer eyJ0eXAiOiJKV1QiLCJhbGciOiJIUzI1NiJ9.eyJ1c2VyX2lkIjoxLCJ1c2VybmFtZSI6InN4aW1hZGEiLCJleHAiOjE1MTEwNDg1OTIsImVtYWlsIjoic3hpbWFkYUBnbWFpbC5jb20ifQ.Ln1aWJRWDZg3Rqyaj5CI2xJkxg8sGMFAD3_zp7TgX00
